var subjects = {
  "DAA": "Design and Analysis of Algorithms",
  "OS": "Operating System",
  "IP": "Internet Programming",
  "KE": "Knowledge Engineering",
  "NSM": "Numerical and Statistical Methods",
  "SE": "Software Engineering",
  "OOSE": "Object Oriented Software Engineering",
  "SP": "System Programming",
  "CG": "Computer Graphics",
  "AMM": "Advanced Microprocessors and Microcontrollers",
  "ET": "Electromagnetic Theory",
  "CE": "Communication Engineering II",
  "ES": "Embedded Systems",
  "DSP": "Digital Signal Processing",
  "AIC": "Analog and Integrated Circuits",
};
